apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/mizotakhteh/api:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 0.1
              memory: 100Mi
              ephemeral-storage: 100Mi
            requests:
              cpu: 0.1
              memory: 100Mi
              ephemeral-storage: 100Mi