apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api-route
spec:
  host: api.mizotakhteh.ml
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  to:
    kind: Service
    name: api
  port:
    targetPort: http